import './globals.css'
import classes from './classes.module.scss'
import './layout.scss'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={classes.layout}>{children}</body>
    </html>
  )
}
